---
title: "11_Method"
date: "`r Sys.Date()`"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


# 1. Reproductive simualations

## 1.1 Load previous simulated data and functions

```{r}
library(dplyr)
library(ggplot2)

# locate all simulation and GIMME functions
source("01_DataSimulation.R")

# clean old simulation folders, if any
if (dir.exists("sim_data")) unlink("sim_data", recursive = TRUE)
if (dir.exists("sim_results")) unlink("sim_results", recursive = TRUE)

# recreate folders by gimme()
dir.create("sim_data", showWarnings = FALSE)
dir.create("sim_results", showWarnings = FALSE)
```

```{r}
# run simulation across T and replications
Ts <- c(50, 150, 300)
R <- 20 # repetitions per T

all_res_list <- list()
idx <- 1

for (tt in Ts) {# loop over T
  
  for (rp in 1:R) {# loop over repetitions
    
    cat("Running T =", tt, "rep =", rp, "\n")
    res <- run_one_sim(
      T_obs = tt,
      N = 100,
      p = 8,
      group_cutoff = 0.75,
      seed = 1000 * tt + rp,
      burn_in = 100
    )
    
    res$rep <- rp
    all_res_list[[idx]] <- res
    idx <- idx + 1
    
  }
  
}

all_res <- do.call(rbind, all_res_list)
head(all_res)

# save combined results
if (!dir.exists("results")) dir.create("results")
write.csv(all_res,
          "results/all_results.csv",
          row.names = FALSE)
```
